GetEat/GetEat.WebUI/Controllers/ReviewsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DomainModel;
using DomainModel.Entities;
using GetEat.WebUI.Models;
using Domain;
using Microsoft.AspNet.Identity;

namespace GetEat.WebUI.Controllers
{
    public class ReviewsController : Controller
    {
        private GetEatContext db = new GetEatContext();
        private readonly IAccountService accountService;

        public ReviewsController()
        {
            accountService = new AccountService(new DataUnitOfWork());
        }

        // GET: Reviews
        public ActionResult Index(int id)
        {
            var reviews = db.Reviews.Where(x => x.RestourantId == id).Include(r => r.CommentatorUserProfile);

            var vm = reviews.Select(x => new ReviewViewModel()
            {
                Commentator = x.CommentatorUserProfile.ForeName + " " + x.CommentatorUserProfile.SurName,
                Comment = x.Comment,
                Score = x.Score,
                WrittenDate = x.CreatedDate
            }).OrderByDescending(x=>x.WrittenDate).ToList();

            return PartialView(vm);
        }


        // POST: Reviews/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ReviewViewModel model)
        {
            if (ModelState.IsValid)
            {
                var review = new Review
                {
                    Comment = model.Comment,
                    Score = model.Score,
                    RestourantId = model.RestourantId,
                    CommentatorUserProfileId = accountService.GetUserProfileId(User.Identity.GetUserId()),
                    CreatedDate = DateTime.Now,
                    UpdatedDate = DateTime.Now
                };
                db.Reviews.Add(review);
                db.SaveChanges();
                return RedirectToActionPermanent("Details", "Search", new { id = model.RestourantId });
            }

            return PartialView(model);
        }


        // GET: Reviews/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Review review = db.Reviews.Find(id);
            if (review == null)
            {
                return HttpNotFound();
            }
            return View(review);
        }

        // POST: Reviews/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Review review = db.Reviews.Find(id);
            db.Reviews.Remove(review);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

GetEat/GetEat.WebUI/Controllers/SearchController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DomainModel;
using DomainModel.Entities;

namespace GetEat.WebUI.Controllers
{
    public class SearchController : Controller
    {
        private GetEatContext db = new GetEatContext();

        // GET: Restourants
        public ActionResult Index()
        {
            var restourants = db.Restourants.Include(r => r.Address).Include(r => r.Organisation);
            return View(restourants.ToList());
        }

        // GET: Restourants/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Restourant restourant = db.Restourants.Find(id);
            if (restourant == null)
            {
                return HttpNotFound();
            }
            return View(restourant);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

GetEat/GetEat.WebUI/Views/Search/Details.cshtml
@model DomainModel.Entities.Restourant

@{
    ViewBag.Title = "Details";
}
<div class="container-fluid">
    <div class="logbackground center-content">
        <div class="container">
            <div class="wrap">
                <p class="back-btn">@Html.ActionLink("Back to List", "Index")</p>
            </div>

            <!-- Trigger the modal with a button -->
            <!-- Modal -->
            <div class="modal fade" id="myModal" role="dialog">
                <div class="modal-dialog">

                    <!-- Modal content-->
                    <div class="modal-content text-center">
                        <div class="modal-header ">
                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                            <h4 class="modal-title">Book your table now</h4>
                        </div>
                        <div class="modal-body">

                            <p>Make reservation.</p>
                            <div class="holder-input">
                                <div class="form-group">
                                    <select class="selectpicker form-control">
                                        <option value="1">1 person</option>
                                        <option value="2">2 people</option>
                                        <option value="3">3 people</option>
                                        <option value="4">4 people</option>
                                        <option value="5">5 people</option>
                                        <option value="6">6 people</option>
                                        <option value="7" selected="selected">7 people</option>
                                        <option value="8">8 people</option>
                                        <option value="9">9 people</option>
                                        <option value="10">10 people</option>
                                        <option value="11">11 people</option>
                                        <option value="12">12 people</option>
                                    </select>
                                </div>

                                <div class="form-group">
                                    <div class='input-group datepicker date' id='datetimepicker1'>
                                        <input type='text' class="form-control" />
                                        <span class="input-group-addon">
                                            <span class="glyphicon glyphicon-calendar"></span>
                                        </span>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <div class="input-group timepicker">
                                        <input id="timepicker2" type="text" class="form-control ">
                                        <span class="input-group-addon">
                                            <i class="glyphicon glyphicon-time"></i>
                                        </span>
                                    </div>
                                </div>
                            </div>

                            <div class="modal-footer">
                                <button type="submit" class="btn popupBtn" data-dismiss="modal">Reserv</button>
                            </div>
                        </div>
                    </div>

                </div>

            </div>

            <div class="row">
                <div class="col-md-6 center-content">
                    <div class="review">
                        <div class="restorant">
                            <div class="text-center">
                                <h3>Raffy Bar & Gelato Park</h3>
                                <div class="form-group">
                                    @if (User.Identity.IsAuthenticated)
                                    {
                                        <div>
                                            <button type="button" class="book" data-toggle="modal" data-target="#myModal">book table here</button>
                                        </div>
                                    }
                                    else
                                    {
                                        <div class="loginbtn">
                                            <ul class="list-inline">
                                                <li><p>You have to </p></li>
                                                <li class="back-btn"><a class="logForm" href="/Account/Login" id="loginLink">Log in</a></li>
                                                <li><p> to book restourant</p></li>
                                            </ul>
                                        </div>
                                    }

                                    <div id="rating">
                                        <ul class="stars">
                                            @{
                                                var score = Model.Reviews.Count > 0 ? Model.Reviews.Average(x => x.Score) : 0;
                                            }
                                            @for (int i = 1; i <= 5; i++)
                                            {
                                                if (score >= i)
                                                {
                                                    <li class="raiting-star active">★</li>
                                                }
                                                else
                                                {
                                                    <li class="raiting-star">★</li>
                                                }
                                            }

                                        </ul>
                                    </div>
                                </div>
                            </div>
                            <div class="middle">
                                <span class="glyphicon glyphicon-map-marker info"><strong> Location: </strong> Simeonovsko shose bul.</span>
                                <span class="glyphicon glyphicon-cutlery info"><strong> Cuisine: </strong> Sushi, Fish, Seafood</span>
                            </div>
                        </div>

                        <article class="overview">
                            <h4 class="text-center">Introduction</h4>
                            <p>
                                The menu at Raffy offers a selection of exciting dishes cooked with the most seasonal of ingredients. Dishes including fish and seafood classics are served with modern flair, in a warm and relaxed atmosphere. Elsewhere on the menu, find rustic meat dishes and a selection of moreish sharing platters.
                                An extensive wine list is on hand to complement the food, with a carefully chosen selection of Italian bottles.
                            </p>
                        </article>
                        @*<p>
                                @Model.Organisation.Name
                                @Model.Description
                                @Model.Name
                                @Model.Address.Neighborhood
                                @Model.Address.Street
                                @Model.Address.Number
                                @Model.Address.City
                                @Model.Address.Country
                            </p>*@
                    </div>
                </div>
                <div class="col-md-6 center-content">
                    <div class="review">
                        <div id="myCarousel" class="carousel slide" data-ride="carousel">
                            <!-- Indicators -->
                            <ol class="carousel-indicators">
                                <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                                <li data-target="#myCarousel" data-slide-to="1"></li>
                                <li data-target="#myCarousel" data-slide-to="2"></li>
                                <li data-target="#myCarousel" data-slide-to="3"></li>
                                <li data-target="#myCarousel" data-slide-to="4"></li>
                                <li data-target="#myCarousel" data-slide-to="5"></li>
                            </ol>

                            <!-- Wrapper for slides -->
                            <div class="carousel-inner" role="listbox">

                                <div class="item active">
                                    <img  src="~/Content/images/gallery-r.jpg" alt="">
                                </div>
                              

                                <div class="item">
                                    <img src="~/Content/images/gallery-re.jpg" alt="">
                                </div>
                                

                                <div class="item">
                                    <img  src="~/Content/images/gallery-res.jpg" alt="">
                                </div>
                              

                                <div class="item">
                                    <img src="~/Content/images/gallery-rest.jpg" alt="">
                                </div>
                                <div class="item">
                                    <img src="~/Content/images/gallery-restour.jpg" alt="">
                                </div>
                                <div class="item">
                                    <img src="~/Content/images/gallery-restoura.jpg" alt="">
                                </div>
                            </div>
                          

                            <!-- Left and right controls -->
                            <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
                                <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                                <span class="sr-only">Previous</span>
                            </a>
                            <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
                                <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                                <span class="sr-only">Next</span>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col map" id="map"></div>
            </div>
            <div class="row">
                <div class="col">
                    <div class="comment-box">
                        <h3>Reviews</h3>

                            @if (User.Identity.IsAuthenticated)
                            {
                                @Html.Partial("~/Views/Reviews/Create.cshtml", new ReviewViewModel() { RestourantId = Model.Id })
                            }
                            else
                            {
                                <div>
                                    <ul class="list-inline">
                                        <li><p class="comment">You have to </p></li>
                                        <li class="back-btn"><a class="logForm" href="/Account/Login" id="loginLink">Log in</a></li>
                                        <li><p>to write comment.</p></li>
                                    </ul>
                                </div>
                            }

                            @Html.Action("Index", "Reviews", new { id = Model.Id })
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section scripts {
    <script type="text/javascript" src="~/Scripts/geteat/home.js"></script>
    <script>
        function mapInitialise() {
            var mapOptions = {
                center: new google.maps.LatLng(42.631011, 23.333508),
                zoom: 18,
                mapTypeId: google.maps.MapTypeId.satellite
            }
            var map = new google.maps.Map(document.getElementById("map"), mapOptions);
        }
       
    </script>
    <script src="https://maps.googleapis.com/maps/api/js?callback=mapInitialise&key=AIzaSyACtwzGqclUR7OIYSgdQDfQg2G03YDoass"></script>

}

GetEat/GetEat.WebUI/Views/Search/Index.cshtml
@model IEnumerable<DomainModel.Entities.Restourant>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>
<div class="container-fluid">
    <div class="companibkgr">
        <div class="container text-center">
            <div class="row wrap">
                <div class="ui-widget">
                    <form action="/Home/Search" method="post">
                        <div class="responsive searchbar">
                            <label class="searchbar-label" for="city">Find</label>
                            <input id="city" class="dropdown-toggle" placeholder="place, city">
                            <span>|</span>
                            <label class="searchbar-label" for="cuisine">Kitchen</label>
                            <input id="cuisine" class="dropdown-toggle" type="text" placeholder="type sushi, french...">
                            <button class="dropdown-toggle buttonGet" type="submit" value="submit"> Search </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        @foreach (var item in Model)
            {
            <div class="restorant-box text-center">
                <div class="thumbnail col-md-3 col-sm-2">
                    <div>

                        <a class="restorantList" href="/Search/Details/@item.Id">

                            @Html.DisplayFor(modelItem => item.Name)

                            <img src="~/Content/images/gallery-res.jpg" alt="">


                            <div id="rating">
                                <ul class="stars">
                                    @{
                                        var score = item.Reviews.Count > 0 ? item.Reviews.Average(x => x.Score) : 0;
                                    }
                                    @for (int i = 1; i <= 5; i++)
                                    {
                                        if (score >= i)
                                        {
                                            <li class="raiting-star active">★</li>
                                        }
                                        else
                                        {
                                            <li class="raiting-star">★</li>
                                        }
                                    }

                                </ul>
                            </div>
                            <div class="caption">
                                <p>
                                    @Html.DisplayFor(modelItem => item.Address.Neighborhood)
                                    @Html.DisplayFor(modelItem => item.Address.Street)
                                    @Html.DisplayFor(modelItem => item.Address.Number)
                                    @Html.DisplayFor(modelItem => item.Address.City)
                                    @Html.DisplayFor(modelItem => item.Address.Country)
                                </p>
                            </div>
                        </a>
                        @*@Html.ActionLink("see more", "Details", new { id = item.Id }) |*@
                    </div>
                </div>
            </div>
                                        }


    </div>
</div>


@section scripts {
    <script type="text/javascript" src="~/Scripts/geteat/home.js">

    </script>
}