GetEat/GetEat.WebUI/Controllers/RestourantsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DomainModel;
using DomainModel.Entities;

namespace GetEat.WebUI.Controllers
{
    public class RestourantsController : Controller
    {
        private GetEatContext db = new GetEatContext();

        // GET: Restourants
        public ActionResult Index()
        {
            var restourants = db.Restourants.Include(r => r.Address).Include(r => r.Organisation);
            return View(restourants.ToList());
        }

        // GET: Restourants/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Restourant restourant = db.Restourants.Find(id);
            if (restourant == null)
            {
                return HttpNotFound();
            }
            return View(restourant);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

GetEat/GetEat.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title </title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
     
    <header class="container-fluid">
        <div id="mayNavbar" class="navbar navbar-inverse navbar-fixed-top" role="navigation">

            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse" aria-expanded="false">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <div class="navbar-header">

                    <a class="navbar-brand navbar-left responsive" href="~/Home/index">
                        <img class="responsive" src="~/Content/images/Logoo.png" />
                    </a>

                </div>
            </div>

            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a class="header-nav-link" href="~/Home/index">Home</a></li>
                    @if (User.Identity.IsAuthenticated && User.IsInRole(RoleNames.Customer))
                    {
                        <li>@Html.ActionLink("Organisation Profile", "Details", "Organisations", new { area = "Companies", id = SessionState.CurrentOrganisationId }, null)</li>
                        <li>@Html.ActionLink("My Restourants", "Index", "Restourants", new { area = "Companies", organisationId = SessionState.CurrentOrganisationId }, null)</li>

                    }
                    else if (User.Identity.IsAuthenticated && User.IsInRole(RoleNames.Adminstrator))
                    {
                        <li>@Html.ActionLink("Kitchens", "Index", "Kitchens", new { area = "Adminstrator" }, null)</li>
                    }
                </ul>
                @Html.Partial("_LoginPartial")
               
            </div>
        </div>
    </header>

    <!--End Daniela Navigation bar-->
    @*<div class="container body-content">*@
    @RenderBody()
    @*<hr class="hidden"/>*@
    @*<footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>*@
    <footer>
        <div class="responsive navbar footer" role="navigation">
            <div class="navbar-header">
                <ul class="nav navbar-nav ">
                    <li><a href="#">About us</a></li>
                    <li><a href="#">Terms and conditions</a></li>
                    <li><a href="../Home/Contact">Contact us</a></li>
                    
                </ul>
            </div>

        </div>
    </footer>
    @*</div>*@

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>